version: '3'
services:
  traefik:
    image: traefik:latest
    restart: always
    container_name: irpl-cuttube-traefik
    command:
      - --entrypoints.web.address=:80
        #- --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --api.insecure=true
        #- --certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory
        #- --certificatesresolvers.leresolver.acme.caserver=https://acme-v02.api.letsencrypt.org/directory
        #- --certificatesresolvers.leresolver.acme.email=info@vedanshis.com
        #- --certificatesresolvers.leresolver.acme.storage=/tls/acme.json
        #- --certificatesresolvers.leresolver.acme.tlschallenge=true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./tls:/tls"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    networks:
      - web
      - cuttube_network
  # nats:
  #   image: nats:latest
  #   container_name: irpl-kanban-nats
  #   network_mode: "host"
  #   restart: always

  db:
    image: postgres:latest
    container_name: irpl-rubber-kanban-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      
  dbhelper:
    # build: ../kanban-dao/
    image: irpl.com/rubber-kanban-dao
    container_name: irpl-rubber-kanban-dao
    network_mode: "host"
    restart: always
    # depends_on:
    #   # - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      DBHELPER_PORT: ${DBHELPER_PORT}
      
  restsrv:
    # build: ../kanban-rest/
    image: irpl.com/rubber-kanban-rest
    container_name: irpl-rubber-kanban-rest
    network_mode: "host"
    restart: always
    depends_on:
      - dbhelper
    environment:
      DBHELPER_HOST: ${DBHELPER_HOST}
      DBHELPER_PORT: ${DBHELPER_PORT}
      RESTSRV_PORT: ${RESTSRV_PORT}

  web:
    # build: ../kanban-web/
    image: irpl.com/rubber-kanban-web
    network_mode: "host"
    container_name: irpl-rubber-kanban-web
    depends_on:
      - dbhelper
    restart: always
    environment:
      BROKER: ${BROKER}
      RESTSRV_HOST: ${RESTSRV_HOST}
      RESTSRV_PORT: ${RESTSRV_PORT} 
      DBHELPER_HOST: ${DBHELPER_HOST}
      DBHELPER_PORT: ${DBHELPER_PORT}
      WEBSRV_PORT: ${WEBSRV_PORT}
      COOKIE_ID: ${COOKIE_ID}
      DOMAIN: ${DOMAIN}
      HOME_URL: ${HOME_URL}
    volumes:
      - ./static:/go-rest-server/kanban-web/static
      - /kanban:/kanban
   

