version: '3'
services:
  nats:
    image: nats:latest
    container_name: irpl-kanban-nats
    ports:
      - "${NATS_PORT}:4222"
    restart: always

  db:
    image: postgres:latest
    container_name: irpl-rubber-kanban-db
    restart: always
    ports:
      - "${DB_PORT}:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      
  dbhelper:
    build: ../kanban-dao/
    image: irpl.com/rubber-kanban-dao
    container_name: irpl-rubber-kanban-dao
    network_mode: "host"
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_NAME}
      DBHELPER_PORT: ${DBHELPER_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      
  restsrv:
    build: ../kanban-rest/
    image: irpl.com/rubber-kanban-rest
    container_name: irpl-rubber-kanban-rest
    network_mode: "host"
    restart: always
    depends_on:
      - dbhelper
      - db
    environment:
      DBHELPER_HOST: ${DBHELPER_HOST}
      DBHELPER_PORT: ${DBHELPER_PORT}
      RESTSRV_PORT: ${RESTSRV_PORT}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  web:
    build: ../kanban-web/
    image: irpl.com/rubber-kanban-web
    network_mode: "host"
    container_name: irpl-rubber-kanban-web
    depends_on:
      - dbhelper
      - db
      - restsrv
    restart: always
    environment:
      BROKER: ${BROKER}
      RESTSRV_HOST: ${RESTSRV_HOST}
      RESTSRV_PORT: ${RESTSRV_PORT} 
      DBHELPER_HOST: ${DBHELPER_HOST}
      DBHELPER_PORT: ${DBHELPER_PORT}
      WEBSRV_PORT: ${WEBSRV_PORT}
      COOKIE_ID: ${COOKIE_ID}
      DOMAIN: ${DOMAIN}
      HOME_URL: ${HOME_URL}
    volumes:
      - ./static:/go-rest-server/kanban-web/static
      - /RUBBER:/RUBBER
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
   
